// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxcTorDPrDCKNoGM-nQMhT5XvB3bonakI',
    appId: '1:609543712112:web:609a321ddd9e055d7673b5',
    messagingSenderId: '609543712112',
    projectId: 'shopease-49097',
    authDomain: 'shopease-49097.firebaseapp.com',
    storageBucket: 'shopease-49097.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLtyxbPmenseH_mv6KwlznnshOnN3I0vY',
    appId: '1:609543712112:android:e868030a8523fcee7673b5',
    messagingSenderId: '609543712112',
    projectId: 'shopease-49097',
    storageBucket: 'shopease-49097.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnYf0uUUE0RNZybmoibAmSDJuczEZ-_K0',
    appId: '1:609543712112:ios:f935fb38ef12f3f67673b5',
    messagingSenderId: '609543712112',
    projectId: 'shopease-49097',
    storageBucket: 'shopease-49097.firebasestorage.app',
    iosBundleId: 'com.example.shopEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnYf0uUUE0RNZybmoibAmSDJuczEZ-_K0',
    appId: '1:609543712112:ios:f935fb38ef12f3f67673b5',
    messagingSenderId: '609543712112',
    projectId: 'shopease-49097',
    storageBucket: 'shopease-49097.firebasestorage.app',
    iosBundleId: 'com.example.shopEase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxcTorDPrDCKNoGM-nQMhT5XvB3bonakI',
    appId: '1:609543712112:web:d86556be4b0312af7673b5',
    messagingSenderId: '609543712112',
    projectId: 'shopease-49097',
    authDomain: 'shopease-49097.firebaseapp.com',
    storageBucket: 'shopease-49097.firebasestorage.app',
  );
}
